apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pdfPod
  name: pdfPod
spec:
  restartPolicy: Always
  containers:
  - name: marker-api
    image: localhost/atlmag/marker-api:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
      hostPort: 8008
      protocol: TCP
    env:
    - name: TORCH_DEVICE
      value: cuda
    - name: PYTHONUNBUFFERED
      value: "1"
    resources:
      limits:
        nvidia.com/gpu=all: 1
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /tmp
      type: Directory
