# node1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/device: /mnt/md1/databases/postgres
    volume.podman.io/driver: local
    volume.podman.io/mount-options: bind
  creationTimestamp: "2025-03-17T21:38:37Z"
  name: db-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
