apiVersion: v1
kind: Pod
metadata:
  name: postgresRestore
  creationTimestamp: "2025-03-06T09:59:34Z"
  labels:
    app: postgresRestore
spec:
  containers:
  - name: db
    image: atlmag/postgres:17
    envFrom:
    - configMapRef:
        name: postgresconf
        optional: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-volume
    - mountPath: /mnt
      name: bak-volume
    ports:
    - containerPort: 5432
      hostPort: 5432
    command: [ "gosu" ]
    args: [ "postgres", "bash", "-c", "'pgbackrest --config=/mnt/pgbackrest.conf --stanza=main --log-level-console=info restore'" ]
  volumes:
  - name: db-volume
    hostPath:
      path: /mnt/md0/databases/postgres
      type: Directory
  - name: bak-volume
    hostPath:
      path: /mnt/md1/bak/postgres
      type: Directory

  restartPolicy: never
