apiVersion: v1
kind: Pod
metadata:
  name: postgresRestore
  creationTimestamp: "2025-03-06T09:59:34Z"
  labels:
    app: postgresRestore
spec:
  containers:
  - name: db
    image: atlmag/pgbackrest:latest
    envFrom:
    - configMapRef:
        name: postgresconf
        optional: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-volume
    - mountPath: /mnt
      name: bak-volume
    command: |
      echo "pgbackrest restore "
      gosu postgres pgbackrest --config=/mnt/pgbackrest.conf --stanza=main --log-level-console=info restore
      echo "done pgbackrest"
  volumes:
  - name: db-volume
    hostPath:
      path: /mnt/md0/databases/postgres
      type: Directory
  - name: bak-volume
    hostPath:
      path: /mnt/md1/bak/postgres
      type: Directory

  restartPolicy: never
