apiVersion: v1
kind: Pod
metadata:
  name: postgres
  creationTimestamp: "2025-03-06T09:59:34Z"
  labels:
    app: postgres
spec:
  containers:
  - name: db
    image: atlmag/postgres:17
    envFrom:
    - configMapRef:
        name: postgresconf
        optional: false
    volumeMounts:
    - mountPath: /etc/postgresql/postgres.conf
      name: pg-conf-file
    - mountPath: /var/lib/postgresql/data
      name: db-volume-pvc
    - mountPath: /mnt
      name: bak-volume-pvc
    ports:
    - containerPort: 5432
      hostPort: 5432
    args: [ "-c", "config_file=/etc/postgresql/postgres.conf" ]
  volumes:
  - name: pg-conf-file
    hostPath:
      path: ./postgres.conf
      type: File
  - name: db-volume-pvc
    persistentVolumeClaim:
      claimName: db-volume
  - name: bak-volume-pvc
    persistentVolumeClaim:
      claimName: bak-volume

  restartPolicy: never
