apiVersion: v1
kind: Pod
metadata:
  name: postgres
  creationTimestamp: "2025-03-06T09:59:34Z"
  labels:
    app: postgres
spec:
  containers:
  - name: db
    image: docker.io/postgres:14.17-bookworm
    envFrom:
    - configMapRef:
        name: postgresconf
        optional: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-volume
    ports:
    - containerPort: 5432
      hostPort: 5432
  - name: pgbackweb
    image: docker.io/eduardolat/pgbackweb:latest
    envFrom:
    - configMapRef:
        name: postgresconf
        optional: false
    volumeMounts:
    - mountPath: /backups
      name: bak-volume
  volumes:
  - hostPath:
    path: /mnt/md0/databases/postgres
    type: Directory
    name: db-volume
  - hostPath:
    path: /mnt/md1/bak/postgres
    type: Directory
    name: bak-volume
  restartPolicy: never
