apiVersion: v1
kind: Pod
metadata:
  name: postgres
  creationTimestamp: "2025-03-06T09:59:34Z"
  labels:
    app: postgres
spec:
  containers:
  - name: db
    image: atlmag/postgres:17
    envFrom:
    - configMapRef:
        name: postgresconf
        optional: false
    volumeMounts:
    - mountPath: /etc/postgresql/postgres.conf
      name: pg-conf-file
    - mountPath: /var/lib/postgresql/data
      name: db-volume
    - mountPath: /mnt
      name: bak-volume
    ports:
    - containerPort: 5432
      hostPort: 5432
    args: [ "-c", "config_file=/etc/postgresql/postgres.conf" ]
  volumes:
  - name: pg-conf-file
    hostPath:
      path: ./postgres.conf
      type: File
  - name: db-volume
    hostPath:
      path: /mnt/md0/databases/postgres
      type: Directory
  - name: bak-volume
    hostPath:
      path: /mnt/md1/bak/postgres
      type: Directory

  restartPolicy: never

