apiVersion: v1
kind: Pod
metadata:
  name: forgejo
  creationTimestamp: "2025-03-27T09:59:34Z"
  labels:
    app: forgejo
spec:
  containers:
  - name: git
    image: codeberg.org/forgejo/forgejo:10.0.3
    volumeMounts:
    - mountPath: /data
      name: db-volume-pvc
    ports:
    - containerPort: 2222
      hostPort: 2222
    - containerPort: 3000
      hostPort: 3000
  volumes:
  - name: data-volume-pvc
    persistentVolumeClaim:
      claimName: data-volume

  restartPolicy: never
