#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # 1. Allow already established traffic
        ct state established,related accept

        # 2. Allow Loopback (Internal communication)
        iif lo accept

        # 3. Allow Ping (ICMP)
        ip protocol icmp accept

        # 4. Management
        tcp dport 22 accept  # SSH

        # 5. K8s Control Plane (Run this on Master)
        tcp dport 6443 accept
        tcp dport { 2379, 2380 } accept

        # 6. K8s Node Communication (Run on all nodes)
        tcp dport 10250 accept
        
        # 7. CNI Overlay (Allow nodes to "tunnel" to each other)
        # If using Calico default:
        ip protocol 4 accept 
        # If using VXLAN:
        # udp dport 4789 accept

        tcp dport 30000-32767 accept
    }

    chain forward {
        type filter hook forward priority 0; policy accept;
    }
}