apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-18T20:12:24Z"
  labels:
    app: speed
  name: speed
spec:
  containers:
  - name: test
    image: lscr.io/linuxserver/speedtest-tracker:latest
    env:
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000
    - name: TZ
      value: Etc/UTC
    - name: APP_KEY
      value: base64:mPtW412n9feqhcCAlxnLHdSFbcNL6MaNwmLMtyLaQgQ=
    - name APP_URL:
      -value: http://small.logout.work:8080
    - name: DB_CONNECTION
      value: sqlite
    ports:
    - containerPort: 8080
      hostPort: 8080

