apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-018T20:12:24Z"
  labels:
    app: speed
  name: speed
spec:
  containers:
  - name: test
    image: lscr.io/linuxserver/speedtest-tracker:latest
    ports:
    - containerPort: 8080
      hostPort: 8080

