services:
  # jellyfin / media
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "8096:8096"
    environment:
      - user 1001:1000
    volumes:
      - /mnt/md1/config/jellyfin:/config
      - /mnt/ssd1/cache:/cache
      - /mnt/md1/data/media:/media
    networks:
      media_network:
        ipv4_address: 172.23.0.2
  
  # sonarr / sonarr
  sonarr:
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1002
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /mnt/md1/config/sonarr:/config
      - /mnt/md1/data:/data
    networks:
      media_network:
        ipv4_address: 172.23.0.3
  
  # deluge / torrents
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    environment:
      - PUID=1003
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /mnt/md1/config/deluge:/config
      - /mnt/md1/data/downloads:/data/downloads
    networks:
      media_network:
        ipv4_address: 172.23.0.4
  # with vpn
  # deluge:
  #   image: binhex/arch-delugevpn
  #   ports:
  #     - "8112:8112"
  #     - "8118:8118"
  #     - "58846:58846"
  #     - "58946:58946"
  #     - "58946:58946/udp"
  #   environment:
  #     - PUID=1003
  #     - PGID=1000
  #     - UMASK=002
  #   volumes:
  #     - /mnt/md1/config/deluge:/config
  #     - /mnt/md1/data/torrents:/data/torrents
  
  # SABnzbd
  SABnzbd:
    image: ghcr.io/hotio/sabnzbd
    ports:
      - "8080:8080"
    environment:
      - PUID=1004
      - PGID=1000
      - UMASK=002
      - TZ="Etc/UTC"
    volumes:
      - /mnt/md1/config/sabnzbd:/config
      - /mnt/md1/data/usenet:/data/usenet
    networks:
      media_network:
        ipv4_address: 172.23.0.5
# network
networks:
  media_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16
         gateway: 172.23.0.1