apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-28T20:12:24Z"
  labels:
    app: mediapod
  name: mediapod
spec:
  containers:
  - name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    ports:
    - containerPort: 8096
      hostPort: 8096
    securityContext:
      runAsGroup: 100
      runAsUser: 1000
    volumeMounts:
    - mountPath: /config
      name: media-config-jellyfin-volume-pvc
      subPath: jellyfin
    - mountPath: /media
      name: media-data-volume-pvc
    - mountPath: /cache
      name: media-cache-volume-pvc
  hostUsers: false
  volumes:
  - name: media-config-jellyfin-volume-pvc
    persistentVolumeClaim:
      claimName: media-config-jellyfin-volume
  - name: media-data-volume-pvc
    persistentVolumeClaim:
      claimName: media-data-volume
  - name: media-cache-volume-pvc
    persistentVolumeClaim:
      claimName: media-cache-volume
