apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-28T20:12:24Z"
  labels:
    app: mediapod
  name: mediapod
spec:
  containers:
  - name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    volumeMounts:
    - mountPath: /config
      name: media-config-volume-pvc
      subPath: jellyfin
    - mountPath: /media
      name: media-data-volume-pvc
      subPath: media
    - mountPath: /cache
      name: media-cache-volume-pvc
    ports:
    - containerPort: 8096
      hostPort: 8096
  - name: deluge
    image: lscr.io/linuxserver/deluge:latest
    volumeMounts:
    - mountPath: /config
      name: media-config-volume-pvc
      subPath: deluge
    - mountPath: /data/downloads
      name: media-data-volume-pvc
      subPath: downloads
    ports:
    - containerport: 8112
      hostPort: 8112
    - containerport: 6881
      hostPort: 6881
    - containerPort: 58846
      hostPort: 58846
  - name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
    - containerPort: 9696
      hostPort: 9696
    volumeMounts:
    - mountPath: /config
      name: media-config-volume-pvc
      subPath: prowlarr
  - name: sonarr
    image: ghcr.io/hotio/sonarr
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    env:
    - name: TZ
      value: "Etc/UTC"
    - name: UMASK
      value: "002"
    ports:
    - containerPort: 8989
      hostPort: 8989
    volumeMounts:
    - mountPath: /config
      name: media-config-volume-pvc
      subPath: sonarr
    - mountPath: /data
      name: media-data-volume-pvc
  volumes:
  - name: media-config-volume-pvc
    persistentVolumeClaim:
      claimName: media-config-volume
  - name: media-data-volume-pvc
    persistentVolumeClaim:
      claimName: media-data-volume
  - name: media-cache-volume-pvc
    persistentVolumeClaim:
      claimName: media-cache-volume
