apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/device: /mnt/ssd1/cache
    volume.podman.io/driver: local
    volume.podman.io/mount-options: bind
  creationTimestamp: "2025-03-29T21:38:37Z"
  name: media-cache-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
