apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-06-12T20:12:24Z"
  labels:
    app: idserverpod
  name: idserverpod
spec:
  containers:
  - name: idserver
    image: atlmag/aspauth
    envFrom:
    - configMapRef:
        name: idServerConf
        optional: false
    ports:
    - containerPort: 8080
      hostPort: 8080
