apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-05T20:12:24Z"
  labels:
    app: webdirpod
  name: webdirpod
spec:
  containers:
  - name: listing
    image: atlmag/web-dir-listing
    envFrom:
    - configMapRef:
        name: webDirConf
        optional: false
    volumeMounts:
    - mountPath: /data
      name: data-volume-pvc
    ports:
    - containerPort: 8000
      hostPort: 8000
  volumes:
  - name: data-volume-pvc
    persistentVolumeClaim:
      claimName: webdir-data-volume
