apiVersion: v1
kind: Pod
metadata:
  name: tor-bridge
  creationTimestamp: "2025-03-01T09:59:34Z"
  labels:
    app: tor-bridge
spec:
  containers:
  - name: debian
    image: docker.io/library/debian:bookworm-slim
    tty: true
    env:
    - name: TERM
      value: xterm
  - name: tor
    image: atlmag/tor-bridge
    volumeMounts:
    - mountPath: /tor/config
      name: tor-config-volume
    - mountPath: /tor/data
      name: tor-data-volume
    ports:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 9050
      hostPort: 9050
    - containerPort: 9057
      hostPort: 9057
  volumes:
  - hostPath:
      path: /home/atle/tor/config
      type: Directory
    name: tor-config-volume
  - hostPath:
      path: /home/atle/tor/data
      type: Directory
    name: tor-data-volume
  restartPolicy: never
