apiVersion: v1
kind: Pod
metadata:
  name: bitcoin-lightning
  creationTimestamp: "2025-03-01T09:59:34Z"
  labels:
    app: bitcoin-lightning
spec:
  containers:
  - name: torproxy
    image: atlmag/torproxy:latest
    volumeMounts:
    - mountPath: /home/tor/data
      name: tor-volume-pvc
      subPath: data
    - mountPath: /home/tor/config
      name: tor-volume-pvc
      subPath: config
  - name: bitcoind
    image: atlmag/bitcoin:latest
    volumeMounts:
    - mountPath: /home/bitcoin/.bitcoin
      name: blockchain-volume-pvc
      subPath: bitcoin
    ports:
    - containerPort: 8333
      hostPort: 8333
  - name: cln
    image: docker.io/elementsproject/lightningd
    volumeMounts:
    - mountPath: /root/.lightning
      name: blockchain-volume-pvc
      subPath: cln
    ports:
    - containerPort: 9736
      hostPort: 9736
    - containerPort: 9738
      hostPort: 9738
  volumes:
  - name: tor-volume-pvc
    persistentVolumeClaim:
      claimName: tor-volume
  - name: blockchain-volume-pvc
    persistentVolumeClaim:
      claimName: blockchain-volume
  restartPolicy: never
