services:
  tor-bridge:
    image: atlmag/tor-bridge:latest
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - /mnt/ssd2/tor:/home/tor/config
    restart: unless-stopped
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.3
  # bitcoincore
  bitcoind:
    image: atlmag/bitcoin:latest
    ports:
      - "8333:8333"
      - "8332:8332"
    environment:
      - UID=1006
      - GID=1001
    volumes:
      - /mnt/ssd2/blockchain/bitcoin:/home/bitcoin/.bitcoin
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.2
  lnd:
    image: lightninglabs/lnd:v0.18.4-beta
    ports:
      - "9735:9735"
      - "10009:10009"
    volumes:
      - /mnt/ssd2/blockchain/lnd:/root/.lnd
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.3
# network
networks:
  bitcoin_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
         gateway: 172.24.0.1
