services:
  obfs4-bridge:
    image: atlmag/tor-bridge:latest
    networks:
      - bitcoin_network
    environment:
      - OR_PORT=${OR_PORT:?Env var OR_PORT is not set.}
      - PT_PORT=${PT_PORT:?Env var PT_PORT is not set.}
      - EMAIL=${EMAIL:?Env var EMAIL is not set.}
      - NICKNAME=torbtclnd666
    volumes:
      - /mnt/ssd2/tor:/var/lib/tor
    ports:
      - ${OR_PORT}:${OR_PORT}
      - ${PT_PORT}:${PT_PORT}
    restart: unless-stopped
  # bitcoincore
  bitcoind:
    image: atlmag/bitcoin:latest
    ports:
      - "8333:8333"
      - "8332:8332"
    environment:
      - UID=1006
      - GID=1001
    volumes:
      - /mnt/ssd2/blockchain/bitcoin:/home/bitcoin/.bitcoin
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.2
  lnd:
    image: lightninglabs/lnd:v0.18.4-beta
    ports:
      - "9735:9735"
      - "10009:10009"
    volumes:
      - /mnt/ssd2/blockchain/lnd:/root/.lnd
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.3
# network
networks:
  bitcoin_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
         gateway: 172.24.0.1
