services:
  lnd:
    image: lightninglabs/lnd:v0.18.4-beta
    ports:
    - "9735:9735"
    - "10009:10009"
    volumes:
    - /home/blockchain/lnd:/root/.lnd
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.3

# network
networks:
  bitcoin_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.24.0.0/16
        gateway: 172.24.0.1
