services:
  # bitcoincore
  bitcoind:
    image: atlmag/bitcoin:latest
    ports:
      - "8333:8333"
      - "8332:8332"
    environment:
      - UID=1006
      - GID=1001
    volumes:
      - /mnt/ssd2/blockchain/bitcoin:/home/bitcoin/.bitcoin
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.2
  lnd:
    image: lightninglabs/lnd:v0.18.4-beta
    ports:
      - "9735:9735"
      - "10009:10009"
    volumes:
      - /mnt/ssd2/blockchain/lnd:/root/.lnd
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.3
  tor-proxy:
    image: atlmag/torproxy:latest
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - /mnt/ssd2/tor/config:/home/tor/config
      - /mnt/ssd2/tor/data:/home/tor/data
    restart: unless-stopped
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.4
  core-lightning:
    image: elementsproject/lightningd
    ports:
      - "9736:9736"
      - "9737:9737"
    volumes:
      - /mnt/ssd2/blockchain/lightning:/root/.lightning
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.5

# network
networks:
  bitcoin_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
         gateway: 172.24.0.1
