services:
  # bitcoincore
  bitcoind:
    image: atlmag/bitcoin:latest
    ports:
      - "8333:8333"
      - "8332:8332"
    environment:
      - UID=1006
      - GID=1001
    volumes:
      - /mnt/ssd2/blockchain/bitcoin:/home/bitcoin/.bitcoin
    networks:
      bitcoin_network:
        ipv4_address: 172.24.0.2
# network
networks:
  bitcoin_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
         gateway: 172.24.0.1
