FROM debian:bookworm-slim
ARG version=28.1
ARG datadir=/home/bitcoin/.bitcoin

ARG UID=101
ARG GID=101

ENV BITCOIN_VERSION=$version

# untar and remove tar
RUN apt update -y \
  && apt upgrade -y \
  && apt install -y wget \
  && apt install iproute2

WORKDIR /opt
RUN wget https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
RUN tar xvf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
RUN rm bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz

RUN apt remove -y wget
RUN apt install -y gosu --no-install-recommends
RUN apt autoremove
RUN apt clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY entrypoint.sh .

# data folder and user
ENV BITCOIN_DATA=$datadir
ENV PATH=/opt/bitcoin-${BITCOIN_VERSION}/bin:$PATH

RUN groupadd --gid ${GID} bitcoin \
  && useradd --create-home --no-log-init -u ${UID} -g ${GID} bitcoin

RUN mkdir -p "${BITCOIN_DATA}"
RUN chown -R bitcoin:bitcoin "${BITCOIN_DATA}"

RUN chmod 770 "${BITCOIN_DATA}"

VOLUME ["/home/bitcoin/.bitcoin"]
EXPOSE 8332 8333

ENTRYPOINT ["./entrypoint.sh"]
RUN bitcoind -version | grep "Bitcoin Core version v${BITCOIN_VERSION}"
CMD ["bitcoind"]