ARG version=28.1
ARG datadir=/home/bitcoin/.bitcoin
ARG UID=1000
ARG GID=1001

FROM debian:bookworm-slim
ENV BITCOIN_VERSION=$version

RUN echo "VERSION=${version},UID=${UID},GID=${GID}"

# untar and remove tar
RUN apt update \
  && apt upgrade \
  && apt install -y wget

WORKDIR /opt
RUN wget https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
RUN tar xvf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
RUN rm bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz

# data folder and user
ENV BITCOIN_DATA=$datadir
ENV PATH=/opt/bitcoin-${BITCOIN_VERSION}/bin:$PATH

RUN groupadd --gid ${GID} bitcoin \
  && useradd --create-home --no-log-init -u ${UID} -g ${GID} bitcoin

RUN mkdir -p "${BITCOIN_DATA}"
RUN chown -R bitcoin:bitcoin "${BITCOIN_DATA}"

RUN chmod 770 "${BITCOIN_DATA}"

COPY --from=base /opt/bitcoin-${BITCOIN_VERSION} /opt/bitcoin-${BITCOIN_VERSION}

VOLUME ["/home/bitcoin/.bitcoin"]
EXPOSE 8332 8333 18332 18333 18443 18444 38333 38332

USER bitcoin
CMD bitcoind -datadir=${BITCOIN_DATA}
