FROM debian:bookworm-slim as base

RUN apt update \
  && apt upgrade \
  && apt install -y wget

ARG TARGETPLATFORM
ENV BITCOIN_VERSION=28.1

WORKDIR /opt
RUN wget https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
RUN tar xvf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz

# Second stage
FROM debian:bookworm-slim as final

ARG UID=1000
ARG GID=1000

ENV BITCOIN_DATA=/home/bitcoin/.bitcoin
ENV BITCOIN_VERSION=28.1
ENV PATH=/opt/bitcoin-${BITCOIN_VERSION}/bin:$PATH

RUN groupadd --gid ${GID} bitcoin \
  && useradd --create-home --no-log-init -u ${UID} -g ${GID} bitcoin \
  && apt-get update -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=base /opt/bitcoin-${BITCOIN_VERSION} /opt/bitcoin-${BITCOIN_VERSION}

VOLUME ["/home/bitcoin/.bitcoin"]
EXPOSE 8332 8333 18332 18333 18443 18444 38333 38332

RUN bitcoind -version"
CMD ["bitcoind"]