apiVersion: v1
kind: Pod
metadata:
  name: bitcoin-lightning
  creationTimestamp: "2025-03-01T09:59:34Z"
  labels:
    app: bitcoin-lightning
spec:
  containers:
  - name: torproxy
    image: atlmag/torproxy:latest
    volumeMounts:
    - mountPath: /home/tor/data
      name: tor-data-volume
    - mountPath: /home/tor/config
      name: tor-config-volume
  - name: bitcoind
    image: atlmag/bitcoin:latest
    volumeMounts:
    - mountPath: /home/bitcoin/.bitcoin
      name: bitcoin-data-volume
    ports:
    - containerPort: 8333
      hostPort: 8333
  - name: lnd
    image: docker.io/lightninglabs/lnd:v0.18.5-beta
    volumeMounts:
    - mountPath: /root/.lnd
      name: lnd-data-volume
    - mountPath: /mnt
      name: bak-volume
    ports:
    - containerPort: 9735
      hostPort: 9735
  - name: cln
    image: docker.io/elementsproject/lightningd
    volumeMounts:
    - mountPath: /root/.lightning
      name: cln-data-volume
    - mountPath: /mnt
      name: bak-volume
    ports:
    - containerPort: 9736
      hostPort: 9736
  volumes:
  - name: tor-config-volume
    hostPath:
      path: /mnt/ssd2/tor/config
      type: Directory
  - name: tor-data-volume
    hostPath:
      path: /mnt/ssd2/tor/data
      type: Directory
  - name: bitcoin-data-volume
    hostPath:
      path: /mnt/ssd2/blockchain/bitcoin
      type: Directory
  - name: lnd-data-volume
    hostPath:
      path: /mnt/ssd2/blockchain/lnd
      type: Directory
  - name: cln-data-volume
    hostPath:
      path: /mnt/ssd2/blockchain/cln
      type: Directory
  - name: bak-volume
    hostPath:
      path: /mnt/md1/bak/bitcoin-lightning/opdb
      type: Directory
  restartPolicy: never
