apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/atle/tor/html:Z
  name: bitcoin-lightning
  creationTimestamp: "2025-03-01T09:59:34Z"
  labels:
    app: bitcoin-lightning
spec:
  containers:
  - name: debian
    image: docker.io/library/debian:bookworm-slim
    tty: true
    env:
    - name: TERM
      value: xterm
  - name: nginx
    image: docker.io/nginxinc/nginx-unprivileged:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html-volume
    ports:
    - containerPort: 8080
      hostPort: 8081
  volumes:
  - hostPath:
      path: /home/atle/tor/html
      type: Directory
    name: html-volume
  restartPolicy: never
