apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-18T20:12:24Z"
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - name: test
    image: nginxinc/nginx-unprivileged:mainline-trixie
    ports:
    - containerPort: 8080
      hostPort: 8080

