apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-02-28T20:12:24Z"
  labels:
    app: docspod
  name: docspod
spec:
  containers:
  - name: app
    image: atlmag/documentdb:latest
    envFrom:
    - configMapRef:
        name: docsConf
        optional: false
    ports:
    - containerPort: 8080
      hostPort: 8082
