apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-03-08T19:22:54Z"
  labels:
    app: nginx-test
  name: nginx-test
  namespace: default
  resourceVersion: "1553"
  uid: 30eddf6f-2f7f-4e0c-bf04-b7b63e4b8824
spec:
  clusterIP: 10.104.9.215
  clusterIPs:
  - 10.104.9.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30288
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
