apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 3a0add826a2a8b657d5da1e7e40c08d089b5d0da4787f820f4cb874295e6584a
    cni.projectcalico.org/podIP: 10.244.36.193/32
    cni.projectcalico.org/podIPs: 10.244.36.193/32
  creationTimestamp: "2026-03-08T19:22:38Z"
  generateName: nginx-test
  generation: 1
  labels:
    app: nginx-test
    pod-template-hash: 6ff8854996
  name: nginx-test-6ff8854996-2tcvq
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-test-6ff8854996
    uid: 8e47694f-f59a-4ea6-b8ad-6451e2ed104e
  resourceVersion: "1524"
  uid: 4e512f64-760d-42b3-bbfa-884296c1b375
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jm5ls
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker-01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-jm5ls
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-03-08T19:22:40Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-03-08T19:22:38Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-03-08T19:22:40Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-03-08T19:22:40Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-03-08T19:22:38Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ca2d0e3da73247b0650079fe135216cfc8b188e688e9b5bd0ac33a7cd4ff1d0c
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:0236ee02dcbce00b9bd83e0f5fbc51069e7e1161bd59d99885b3ae1734f3392e
    lastState: {}
    name: nginx
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-08T19:22:39Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jm5ls
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.1.31
  hostIPs:
  - ip: 192.168.1.31
  observedGeneration: 1
  phase: Running
  podIP: 10.244.36.193
  podIPs:
  - ip: 10.244.36.193
  qosClass: BestEffort
  startTime: "2026-03-08T19:22:38Z"
